services:
  # A Docker web service
  - type: web
    name: chatapp-fastapi
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: cd fastapi && pip install -r requirements.txt
    startCommand: cd fastapi && uvicorn main:app --host 0.0.0.0 --port $PORT
